export const actionTypes = {
  CHANGE_EMAIL: "CHANGE_EMAIL",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  CHANGE_INPUT: "CHANGE_INPUT",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  UPDATE_TODOLIST: "UPDATE_TODOLIST",
  CHANGE_LOADING_STATUS: {
    OF_TODOLIST: "OF_TODOLIST",
    OF_LOGIN: "OF_LOGIN",
  },
  CHANGE_ERROR_STATUS: {
    OF_TODOLIST: "OF_TODOLIST",
    OF_LOGIN: "OF_LOGIN",
  },
  CHANGE_LOADING_COUNT: "CHANGE_LOADING_COUNT",
  CHANGE_DISPLAY: {
    OF_INCOMPLETEDLIST: 'OF_INCOMPLETEDLIST',
    OF_COMPLETEDLIST: 'OF_COMPLETEDLIST'
  }
};
